### ISSUE TITLE
Uncertain behavor: non-timestamped messages publish "nan" message_age

### ISSUE THREAD

**Issue by emersonknapp** [ros-tooling/libstatistics_collector#27]
## Description

`message_age` for non-timestamped data publishes statistics with `.nan` as the entry. Not sure that this is correct? Not sure what to expect.

### Expected Behavior

For the `message_age` data not to be published.

### Actual Behavior

```
measurement_source_name: arst
metrics_source: message_age
unit: ms
window_start:
  sec: 1590815243
  nanosec: 833869000
window_stop:
  sec: 1590815245
  nanosec: 835134000
statistics:
- data_type: 1
  data: .nan
- data_type: 3
  data: .nan
- data_type: 2
  data: .nan
- data_type: 5
  data: 0.0
- data_type: 4
  data: .nan
```

## To Reproduce

Use std_msgs/String

## System (please complete the following information)
 - OS: OSX
 - ROS 2 Distro: https://ci.ros2.org/view/packaging/job/packaging_osx/1865/artifact/ws/ros2-package-osx-x86_64.tar.bz2
