### ISSUE TITLE
Uncertain behavior: if published message is of type Header - message_age is not calculated

### ISSUE THREAD

**Issue by emersonknapp** [ros-tooling/libstatistics_collector#28]
## Description

Subcribe to topic of type std_msgs/Header - message_age is till reported as `.nan`

### Expected Behavior

Report topic statistics?

### Actual Behavior

Message_age is `.nan`

## To Reproduce

Publish std_msgs/Header with increasing timestamps, subscribe with topic statistics enabled

## System (please complete the following information)
 - OS: OSX
 - ROS 2 Distro: Foxy fat binaries

**Comment by dabonnie** [comment]
Using the code at https://github.com/emersonknapp/foxytest (thanks for uploading!) I was able to generate and observe statistics by building without any local changes. For example, running `chatterer`, `chatter_stats`, and observing with `ros2 topic echo /staty`:

```
unit: ms
window_start:
  sec: 1591030810
  nanosec: 851118000
window_stop:
  sec: 1591030812
  nanosec: 851673000
statistics:
- data_type: 1
  data: 0.00684931506849315
- data_type: 3
  data: 2.0
- data_type: 2
  data: 0.0
- data_type: 5
  data: 584.0
- data_type: 4
  data: 0.11684056239199982
---
measurement_source_name: topic_stats_test
metrics_source: message_period
unit: ms
window_start:
  sec: 1591030810
  nanosec: 851118000
window_stop:
  sec: 1591030812
  nanosec: 851673000
statistics:
- data_type: 1
  data: 999.5403087478567
- data_type: 3
  data: 1009.0
- data_type: 2
  data: 990.0
- data_type: 5
  data: 583.0
- data_type: 4
  data: 3.1980919333958764
```

Non-NaN data was observed for ~10 minutes.
