### ISSUE TITLE
Millisecond resolution for message_age is not granular enough for simple tests

### ISSUE THREAD

**Issue by emersonknapp** [ros-tooling/libstatistics_collector#29]
## Description

Publish a geometry_msgs/PoseStamped in one shell, and subscribe in another.
Message age is only ever reported as minimum 0ms, maximum 1s - so the average does not feel very meaningful. Since timestamps are reported at nanosecond resolution it might make sense to report stats at ns resolution? System clock isn't nanosecond resolution, likely, but it's likely finer than millisecond.

Example stats message:

```
measurement_source_name: topic_stats_test
metrics_source: message_age
unit: ms
window_start:
  sec: 1590821591
  nanosec: 866668000
window_stop:
  sec: 1590821593
  nanosec: 866916000
statistics:
- data_type: 1
  data: 0.04
- data_type: 3
  data: 1.0
- data_type: 2
  data: 0.0
- data_type: 5
  data: 75.0
- data_type: 4
  data: 0.19595917942265426
```

### Expected Behavior

Reporting message age between 0 and 1 ms

### Actual Behavior
** clear and concise description of what _actually_ happened. include copied logs whenever possible **

## System (please complete the following information)
 - OS: OSX
 - ROS 2 Distro: Foxy fat binaries

** For ROS 2 bugs - please attach a VCS.repos or Dockerfile if possible to help us reproduce the environment **

## Additional context
** Add any other context about the problem here **
