### ISSUE TITLE
The measured values after the decimal point are truncated.

### ISSUE THREAD

**Issue by hsgwa** [ros-tooling/libstatistics_collector#79]
## Description
"topic period" and "topic age" values after the decimal point are truncated.
For instance, topic age can be zero in the case of intra process communication.

### Expected Behavior
This test package is located [here](https://github.com/hsgwa/intra_process_ping_latency_test)
```
$ ros2 topic echo /topic_statistics
---
metrics_source: message_age
~snip~
statistics:
- data_type: 1 # Average
  data: 0.6033495235235232
- data_type: 3 # Maximum
  data: 1.221165
- data_type: 2 # Minimum
  data: 0.141677 # 0.141 ms
~~
metrics_source: message_period
~~
statistics:
- data_type: 1 # Average
  data: 9.999780017034087
- data_type: 3 #  Maximum
  data: 11.03389
- data_type: 2 # Minimum
  data: 9.125303
~~
---

```

### Actual Behavior
```
metrics_source: message_age
~~
statistics:
- data_type: 1 # Average
  data: 0.021038292719842887
- data_type: 3 #  Maximum
  data: 6.0 # after the decimal point are truncated.
- data_type: 2 # Minimum
  data: 0.0 # 0 ms
~~
metrics_source: message_period
statistics:
- data_type: 1 # Average
  data: 9.495270116868728
- data_type: 3 #  Maximum
  data: 24.0 # after the decimal point are truncated.
- data_type: 2 # Minimum
  data: 3.0
---
```

## To Reproduce
I've implemented test case which measures intra process communication.
```
$ cd ~/ros2_ws/
$ git clone https://github.com/hsgwa/intra_process_ping_latency_test.git src
$ colcon build --packages-select intra_process_ping_latency_test
$ . ~/ros2_ws/install/local_setup.bash
$ ros2 run intra_process_ping_latency_test ping_test
$ ros2 topic echo /topic_statistics # in another terminal
```

## System
 - OS: Ubuntu 20.04.1 LTS (Focal Fossa)
 - ROS 2 Distro: Rolling
